// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZWrOIjEgrCvuKOq23aGk_MgeVNBn9G0',
    appId: '1:817356004783:web:102973e9eff941c3ede35a',
    messagingSenderId: '817356004783',
    projectId: 'salabeauty-42a26',
    authDomain: 'salabeauty-42a26.firebaseapp.com',
    databaseURL:
        'https://salabeauty-42a26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salabeauty-42a26.appspot.com',
    measurementId: 'G-J9F9XGH7L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJBeMl4KYevOckmhM9oSQv3AfDvdbLzM',
    appId: '1:817356004783:android:adb9cd04cf497358ede35a',
    messagingSenderId: '817356004783',
    projectId: 'salabeauty-42a26',
    databaseURL:
        'https://salabeauty-42a26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salabeauty-42a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-o6L10MscDGSdXhniQYE4gGIP0w_ReY',
    appId: '1:817356004783:ios:147a1ef11fa80339ede35a',
    messagingSenderId: '817356004783',
    projectId: 'salabeauty-42a26',
    databaseURL:
        'https://salabeauty-42a26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salabeauty-42a26.appspot.com',
    iosClientId:
        '817356004783-1ptka2a6ubnc7j09gqaau472j1rhn7bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.billApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5-o6L10MscDGSdXhniQYE4gGIP0w_ReY',
    appId: '1:817356004783:ios:147a1ef11fa80339ede35a',
    messagingSenderId: '817356004783',
    projectId: 'salabeauty-42a26',
    databaseURL:
        'https://salabeauty-42a26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salabeauty-42a26.appspot.com',
    iosClientId:
        '817356004783-1ptka2a6ubnc7j09gqaau472j1rhn7bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.billApp',
  );
}
